export const ManProductData  = [
    {
        id: 1,
        name: 'Nike Air Max 270',
        brand: 'Nike',
        category: 'Running',
        subCategory: 'Lifestyle',
        price: 159.99,
        originalPrice: 199.99,
        discount: 20,
        rating: 4.8,
        reviews: 1248,
        sizes: ['8', '9', '10', '11', '12'],
        colors: ['#000000', '#3B82F6', '#EF4444'],
        image: '/man.png',
        badge: 'BEST SELLER',
        inStock: true,
        deliveryTime: '2-4 days',
        features: ['Air Cioning', 'Breathable Upper', 'Lightweight']
    },
    {
        id: 2,
        name: 'Adidas Ultraboost 22',
        brand: 'Adidas',
        category: 'Running',
        subCategory: 'Performance',
        price: 179.99,
        originalPrice: 199.99,
        discount: 10,
        rating: 4.9,
        reviews: 956,
        sizes: ['7.5', '8.5', '9.5', '10.5', '11'],
        colors: ['#FFFFFF', '#000000', '#10B981'],
        image: '/man2.png',
        badge: 'TRENDING',
        inStock: true,
        deliveryTime: '1-3 days',
        features: ['Boost Technology', 'Primeknit Upper', 'Continental Rubber']
    },
    {
        id: 3,
        name: 'Puma RS-X',
        brand: 'Puma',
        category: 'Lifestyle',
        subCategory: 'Casual',
        price: 119.99,
        originalPrice: 139.99,
        discount: 14,
        rating: 4.6,
        reviews: 742,
        sizes: ['8', '9', '10', '11'],
        colors: ['#8B5CF6', '#F97316', '#6B7280'],
        image: '/man3.png',
        badge: 'NEW',
        inStock: true,
        deliveryTime: '3-5 days',
        features: ['Chunky Design', 'Comfortable', 'Retro Style']
    },
    {
        id: 4,
        name: 'New Balance 990v5',
        brand: 'New Balance',
        category: 'Running',
        subCategory: 'Premium',
        price: 174.99,
        originalPrice: 174.99,
        discount: 0,
        rating: 4.9,
        reviews: 1123,
        sizes: ['7', '8', '9', '10', '11', '12'],
        colors: ['#6B7280', '#000000'],
        image: '/man4.png',
        badge: 'BEST SELLER',
        inStock: true,
        deliveryTime: '4-6 days',
        features: ['Made in ', 'ENCAP Midsole', 'Pigskin Leather']
    },
    {
        id: 5,
        name: 'Nike Air Force 1',
        brand: 'Nike',
        category: 'Lifestyle',
        subCategory: 'Classic',
        price: 99.99,
        originalPrice: 110.99,
        discount: 10,
        rating: 4.7,
        reviews: 2845,
        sizes: ['7.5', '8.5', '9.5', '10.5', '11.5', '12'],
        colors: ['#FFFFFF', '#000000'],
        image: '/man5.png',
        badge: 'BEST SELLER',
        inStock: true,
        deliveryTime: '2-4 days',
        features: ['Classic Design', 'Air Cioning', 'Leather Upper']
    },
    {
        id: 6,
        name: 'Adidas NMD_R1',
        brand: 'Adidas',
        category: 'Lifestyle',
        subCategory: 'Streetwear',
        price: 139.99,
        originalPrice: 159.99,
        discount: 13,
        rating: 4.5,
        reviews: 891,
        sizes: ['8', '9', '10', '11'],
        colors: ['#3B82F6', '#000000', '#EF4444'],
        image: '/man2.png',
        badge: 'TRENDING',
        inStock: false,
        deliveryTime: 'Restocking Soon',
        features: ['Boost Midsole', 'Primeknit Upper', 'EVA Plugs']
    },
    {
        id: 7,
        name: 'Converse Chuck 70',
        brand: 'Converse',
        category: 'Lifestyle',
        subCategory: 'Classic',
        price: 89.99,
        originalPrice: 95.99,
        discount: 6,
        rating: 4.8,
        reviews: 1672,
        sizes: ['7', '8', '9', '10', '11', '12'],
        colors: ['#000000', '#FFFFFF', '#EF4444'],
        image: '/man3.png',
        badge: 'CLASSIC',
        inStock: true,
        deliveryTime: '1-3 days',
        features: ['Canvas Upper', 'OrthoLite Insole', 'Classic Design']
    },
    {
        id: 8,
        name: 'Reebok Nano X2',
        brand: 'Reebok',
        category: 'Training',
        subCategory: 'CrossFit',
        price: 129.99,
        originalPrice: 149.99,
        discount: 13,
        rating: 4.7,
        reviews: 534,
        sizes: ['8', '9', '10', '11', '12'],
        colors: ['#000000', '#3B82F6', '#10B981'],
        image: '/man4.png',
        badge: 'NEW',
        inStock: true,
        deliveryTime: '3-5 days',
        features: ['Floatride Foam', 'Flexweave Upper', 'Rope Guard']
    },
]


export const WomanProductData = [
    {
        id: 1,
        name: 'Nike Air Max 270',
        brand: 'Nike',
        category: 'Running',
        subCategory: 'Lifestyle',
        price: 159.99,
        originalPrice: 199.99,
        discount: 20,
        rating: 4.8,
        reviews: 1248,
        sizes: ['8', '9', '10', '11', '12'],
        colors: ['#000000', '#3B82F6', '#EF4444'],
        image: '/man2.png',
        badge: 'BEST SELLER',
        inStock: true,
        deliveryTime: '2-4 days',
        features: ['Air Cioning', 'Breathable Upper', 'Lightweight']
    },
    {
        id: 2,
        name: 'Adidas Ultraboost 22',
        brand: 'Adidas',
        category: 'Running',
        subCategory: 'Performance',
        price: 179.99,
        originalPrice: 199.99,
        discount: 10,
        rating: 4.9,
        reviews: 956,
        sizes: ['7.5', '8.5', '9.5', '10.5', '11'],
        colors: ['#FFFFFF', '#000000', '#10B981'],
        image: '/man3.png',
        badge: 'TRENDING',
        inStock: true,
        deliveryTime: '1-3 days',
        features: ['Boost Technology', 'Primeknit Upper', 'Continental Rubber']
    },
    {
        id: 3,
        name: 'Puma RS-X',
        brand: 'Puma',
        category: 'Lifestyle',
        subCategory: 'Casual',
        price: 119.99,
        originalPrice: 139.99,
        discount: 14,
        rating: 4.6,
        reviews: 742,
        sizes: ['8', '9', '10', '11'],
        colors: ['#8B5CF6', '#F97316', '#6B7280'],
        image: '/man4.png',
        badge: 'NEW',
        inStock: true,
        deliveryTime: '3-5 days',
        features: ['Chunky Design', 'Comfortable', 'Retro Style']
    },
    {
        id: 4,
        name: 'New Balance 990v5',
        brand: 'New Balance',
        category: 'Running',
        subCategory: 'Premium',
        price: 174.99,
        originalPrice: 174.99,
        discount: 0,
        rating: 4.9,
        reviews: 1123,
        sizes: ['7', '8', '9', '10', '11', '12'],
        colors: ['#6B7280', '#000000'],
        image: '/man5.png',
        badge: 'BEST SELLER',
        inStock: true,
        deliveryTime: '4-6 days',
        features: ['Made in ', 'ENCAP Midsole', 'Pigskin Leather']
    },
    {
        id: 5,
        name: 'Nike Air Force 1',
        brand: 'Nike',
        category: 'Lifestyle',
        subCategory: 'Classic',
        price: 99.99,
        originalPrice: 110.99,
        discount: 10,
        rating: 4.7,
        reviews: 2845,
        sizes: ['7.5', '8.5', '9.5', '10.5', '11.5', '12'],
        colors: ['#FFFFFF', '#000000'],
        image: '/man.png',
        badge: 'BEST SELLER',
        inStock: true,
        deliveryTime: '2-4 days',
        features: ['Classic Design', 'Air Cioning', 'Leather Upper']
    },
    {
        id: 6,
        name: 'Adidas NMD_R1',
        brand: 'Adidas',
        category: 'Lifestyle',
        subCategory: 'Streetwear',
        price: 139.99,
        originalPrice: 159.99,
        discount: 13,
        rating: 4.5,
        reviews: 891,
        sizes: ['8', '9', '10', '11'],
        colors: ['#3B82F6', '#000000', '#EF4444'],
        image: '/man2.png',
        badge: 'TRENDING',
        inStock: false,
        deliveryTime: 'Restocking Soon',
        features: ['Boost Midsole', 'Primeknit Upper', 'EVA Plugs']
    },
    {
        id: 7,
        name: 'Converse Chuck 70',
        brand: 'Converse',
        category: 'Lifestyle',
        subCategory: 'Classic',
        price: 89.99,
        originalPrice: 95.99,
        discount: 6,
        rating: 4.8,
        reviews: 1672,
        sizes: ['7', '8', '9', '10', '11', '12'],
        colors: ['#000000', '#FFFFFF', '#EF4444'],
        image: '/man3.png',
        badge: 'CLASSIC',
        inStock: true,
        deliveryTime: '1-3 days',
        features: ['Canvas Upper', 'OrthoLite Insole', 'Classic Design']
    },
    {
        id: 8,
        name: 'Reebok Nano X2',
        brand: 'Reebok',
        category: 'Training',
        subCategory: 'CrossFit',
        price: 129.99,
        originalPrice: 149.99,
        discount: 13,
        rating: 4.7,
        reviews: 534,
        sizes: ['8', '9', '10', '11', '12'],
        colors: ['#000000', '#3B82F6', '#10B981'],
        image: '/man4.png',
        badge: 'NEW',
        inStock: true,
        deliveryTime: '3-5 days',
        features: ['Floatride Foam', 'Flexweave Upper', 'Rope Guard']
    },
]