const { Zap, Footprints, Flame, Star, Shovel } = require("lucide-react");

export const collections = [
    {
        title: "Running Shoes",
        description: "Speed, stability, and performance built for athletes and daily runners.",
        image: "/man.png",
        icon: <Shovel className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "24 Products",
        rating: 4.8,
        reviews: 1247,
        discount: "20% OFF",
        featured: true,
        tags: ["Lightweight", "Breathable", "Durable"],
    },
    {
        title: "Casual Sneakers",
        description: "Comfort meets street style. Perfect for everyday wear with premium materials.",
        image: "/man3.png",
        icon: <Star className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "18 Products",
        rating: 4.6,
        reviews: 892,
        discount: "15% OFF",
        featured: false,
        tags: ["Comfort", "Style", "Versatile"],
    },
    {
        title: "Limited Edition",
        description: "Rare drops, premium builds, and exclusive designs for collectors and enthusiasts.",
        image: "/man2.png",
        icon: <Flame className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "12 Products",
        rating: 4.9,
        reviews: 567,
        discount: "Limited Stock",
        featured: true,
        tags: ["Exclusive", "Premium", "Collector"],
    },
    {
        title: "Training Shoes",
        description: "Grip, balance, and durability for intense workouts and professional sports.",
        image: "/man4.png",
        icon: <Footprints className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "16 Products",
        rating: 4.7,
        reviews: 734,
        discount: "25% OFF",
        featured: false,
        tags: ["Grip", "Support", "Flexible"],
    },
    {
        title: "Basketball Shoes",
        description: "High-performance footwear designed for court dominance and superior ankle support.",
        image: "/man5.png",
        icon: <Zap className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "14 Products",
        rating: 4.8,
        reviews: 621,
        discount: "30% OFF",
        featured: true,
        tags: ["Performance", "Support", "Court"],
    },
    {
        title: "Running Shoes",
        description: "Speed, stability, and performance built for athletes and daily runners.",
        image: "/man.png",
        icon: <Shovel className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "24 Products",
        rating: 4.8,
        reviews: 1247,
        discount: "20% OFF",
        featured: true,
        tags: ["Lightweight", "Breathable", "Durable"],
    },
    {
        title: "Casual Sneakers",
        description: "Comfort meets street style. Perfect for everyday wear with premium materials.",
        image: "/man3.png",
        icon: <Star className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "18 Products",
        rating: 4.6,
        reviews: 892,
        discount: "15% OFF",
        featured: false,
        tags: ["Comfort", "Style", "Versatile"],
    },
    {
        title: "Limited Edition",
        description: "Rare drops, premium builds, and exclusive designs for collectors and enthusiasts.",
        image: "/man2.png",
        icon: <Flame className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "12 Products",
        rating: 4.9,
        reviews: 567,
        discount: "Limited Stock",
        featured: true,
        tags: ["Exclusive", "Premium", "Collector"],
    },
    {
        title: "Training Shoes",
        description: "Grip, balance, and durability for intense workouts and professional sports.",
        image: "/man4.png",
        icon: <Footprints className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "16 Products",
        rating: 4.7,
        reviews: 734,
        discount: "25% OFF",
        featured: false,
        tags: ["Grip", "Support", "Flexible"],
    },
    {
        title: "Basketball Shoes",
        description: "High-performance footwear designed for court dominance and superior ankle support.",
        image: "/man5.png",
        icon: <Zap className="w-6 h-6" />,
        gradient: "from-green-500 to-emerald-400",
        bgGradient: "gray-100",
        count: "14 Products",
        rating: 4.8,
        reviews: 621,
        discount: "30% OFF",
        featured: true,
        tags: ["Performance", "Support", "Court"],
    },


];